ExamAndQuiz/Models/Exam.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Exam
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Exam()
    {

        this.ExamQuestions = new HashSet<ExamQuestion>();

        this.ExamOptions = new HashSet<ExamOption>();

        this.ExamResults = new HashSet<ExamResult>();

        this.QuestionBanks = new HashSet<QuestionBank>();

        this.PDFFiles = new HashSet<PDFFile>();

        this.StudentActions = new HashSet<StudentAction>();

        this.StudentOptions = new HashSet<StudentOption>();

    }


    public int ID { get; set; }

    public string Ad { get; set; }

    public int SinifID { get; set; }

    public System.DateTime Tarix { get; set; }

    public string Saat { get; set; }

    public int Muddet_deqiqe { get; set; }

    public bool Status { get; set; }

    public bool Giris { get; set; }

    public string FotoURL { get; set; }

    public string PDFFileUrl { get; set; }

    public int TipParametrID { get; set; }

    public int AdminID { get; set; }

    public string Imtahan { get; set; }



    public virtual Admin Admin { get; set; }

    public virtual ExamTypeParameter ExamTypeParameter { get; set; }

    public virtual Grade Grade { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamOption> ExamOptions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamResult> ExamResults { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuestionBank> QuestionBanks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PDFFile> PDFFiles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StudentAction> StudentActions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StudentOption> StudentOptions { get; set; }

}

}

ExamAndQuiz/Models/ExamType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExamType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ExamType()
    {

        this.ExamTypeParameters = new HashSet<ExamTypeParameter>();

    }


    public int ID { get; set; }

    public string Adi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamTypeParameter> ExamTypeParameters { get; set; }

}

}

ExamAndQuiz/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExamAndQuiz.Models;
using ExamAndQuiz.Tools;

namespace ExamAndQuiz.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ExamController : Controller
    {

        private OnlineExamEntities db = new OnlineExamEntities();

        public ActionResult Index()
        {
            var exams = db.Exams.Include(e => e.Admin).Include(e => e.ExamTypeParameter).Include(e => e.Grade);
            return View(exams.ToList());
        }


        public ActionResult Create()
        {
            ViewBag.AdminID = new SelectList(db.Admins, "ID", "Ad");
            ViewBag.TipParametrID = new SelectList(db.ExamTypeParameters, "ID", "Ad");
            ViewBag.SinifID = new SelectList(db.Grades, "ID", "ID");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Exam exam, HttpPostedFileBase file, HttpPostedFileBase PDF)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/UploadFoto/Exam/"), Path.GetFileName(DateTime.Now.ToString("ddMMyy") + CodeGenerator.Code() + file.FileName));

                    string[] massiv = path.Split('\\');
                    exam.FotoURL = "~/UploadFoto/Exam/" + massiv[massiv.Length - 1];
                    file.SaveAs(path);
                }
                else
                {
                    exam.FotoURL = "~/UploadFoto/Exam/test.jpg";
                }
                if (PDF != null && PDF.ContentLength > 0)
                {
                    string pathPDF = Path.Combine(Server.MapPath("~/UploadPDF/"), Path.GetFileName(DateTime.Now.ToString("ddMMyy") + CodeGenerator.Code() + PDF.FileName));

                    string[] massivPDf = pathPDF.Split('\\');
                    exam.PDFFileUrl = "~/UploadPDF/" + massivPDf[massivPDf.Length - 1];
                    PDF.SaveAs(pathPDF);
                }

                db.Exams.Add(exam);
                db.SaveChanges();

                /*Imtahan Suallari Start*/
                ExamQuestion questions = new ExamQuestion();
                var fennler = db.ExamParameters.Where(x => x.TipParametrID == exam.TipParametrID).OrderBy(x => x.Sira).ToList();
                int sualsira = 1;
                foreach (var item in fennler)
                {
                    for (int i = 0; i < item.UmumiSualSayi; i++)
                    {
                        questions.ImtahanId = exam.ID;
                        questions.FennId = item.FenninID;
                        questions.TipId = exam.TipParametrID;
                        questions.SualSirasi = sualsira;
                        questions.SualMetni = null;
                        questions.Cavablar = null;
                        questions.YaranmaTarixi = DateTime.Now;
                        if (item.AciqSualSayi != 0)
                        {
                            string[] massiv = item.AciqSuallar.Split(',');
                            if (massiv.Contains(sualsira.ToString()))
                            {
                                var Tipid = db.QuestionTypes.FirstOrDefault(x => x.Tip == "Açıq");
                                questions.SualTipi = Tipid.ID;
                            }
                            else
                            {
                                var Tipid = db.QuestionTypes.FirstOrDefault(x => x.Tip == "Qapalı");
                                questions.SualTipi = Tipid.ID;
                            }
                        }
                        else
                        {
                            var Tipid = db.QuestionTypes.FirstOrDefault(x => x.Tip == "Qapalı");
                            questions.SualTipi = Tipid.ID;
                        }
                        db.ExamQuestions.Add(questions);
                        db.SaveChanges();
                        sualsira++;

                    }
                }
                /*Imtahan Suallari End*/


                return RedirectToAction("Index");
            }

            ViewBag.AdminID = new SelectList(db.Admins, "ID", "Ad", exam.AdminID);
            ViewBag.TipParametrID = new SelectList(db.ExamTypeParameters, "ID", "Ad", exam.TipParametrID);
            ViewBag.SinifID = new SelectList(db.Grades, "ID", "ID", exam.SinifID);
            return View(exam);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            ViewBag.AdminID = new SelectList(db.Admins, "ID", "Ad", exam.AdminID);
            ViewBag.TipParametrID = new SelectList(db.ExamTypeParameters, "ID", "Ad", exam.TipParametrID);
            ViewBag.SinifID = new SelectList(db.Grades, "ID", "ID", exam.SinifID);
            return View(exam);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Exam exam, HttpPostedFileBase file, HttpPostedFileBase PDF)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/UploadFoto/Exam/"), Path.GetFileName(DateTime.Now.ToString("ddMMyy") + CodeGenerator.Code() + file.FileName));

                    string[] massiv = path.Split('\\');
                    exam.FotoURL = "~/UploadFoto/Exam/" + massiv[massiv.Length - 1];
                    file.SaveAs(path);
                }

                if (PDF != null && PDF.ContentLength > 0)
                {
                    string pathPDF = Path.Combine(Server.MapPath("~/UploadPDF/"), Path.GetFileName(DateTime.Now.ToString("ddMMyy") + CodeGenerator.Code() + PDF.FileName));

                    string[] massivPDf = pathPDF.Split('\\');
                    exam.PDFFileUrl = "~/UploadPDF/" + massivPDf[massivPDf.Length - 1];
                    PDF.SaveAs(pathPDF);
                }

                db.Entry(exam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AdminID = new SelectList(db.Admins, "ID", "Ad", exam.AdminID);
            ViewBag.TipParametrID = new SelectList(db.ExamTypeParameters, "ID", "Ad", exam.TipParametrID);
            ViewBag.SinifID = new SelectList(db.Grades, "ID", "ID", exam.SinifID);
            return View(exam);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

ExamAndQuiz/Views/Exam/Create.cshtml
@model ExamAndQuiz.Models.Exam

@{
    ViewBag.Title = "Yeni İmtahan";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
}

<h2>Yeni İmtahan</h2>

@using (Html.BeginForm("Create", "Exam", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <input type="hidden" name="@Html.NameFor(x => x.AdminID)" value="@Session["ID"]" />        
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>İmtahanın Adı:<span style="color:red">*</span></p>
                        @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>İmtahan Sinifi:<span style="color:red">*</span></p>
                        @Html.DropDownList("SinifID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SinifID, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>İmtahanın Tarixi:<span style="color:red">*</span></p>
                        @Html.EditorFor(model => model.Tarix, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.Tarix, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>Tip Parametri:<span style="color:red">*</span></p>
                        @Html.DropDownList("TipParametrID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TipParametrID, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>İmtahanın Müddəti(dəqiqə):<span style="color:red">*</span></p>
                        @Html.EditorFor(model => model.Muddet_deqiqe, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                        @Html.ValidationMessageFor(model => model.Muddet_deqiqe, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>İmtahanın Saatı:<span style="color:red">*</span></p>
                        @*@Html.EditorFor(model => model.Saat, new { htmlAttributes = new { @class = "form-control", type = "time" } })*@
                        <input id="maskSample03" type="text" name="Saat" class="form-control" placeholder="Saat: 00:00" data-mask="00:00" required="">
                        @Html.ValidationMessageFor(model => model.Saat, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>Imtahan:<span style="color:red">*</span></p>
                        <select name="@Html.NameFor(x => x.Imtahan)" id="file" class="form-control">
                            <option value="Sınaq">Sınaq</option>
                            @*<option value="value">Quiz</option>*@
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>Foto:<span style="color:red">*</span></p>
                        <input type="file" name="file" id="file" class="form-control" />
                        @Html.ValidationMessageFor(model => model.FotoURL, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>PDF:<span style="color:red">*</span></p>
                        <input type="file" name="PDF" id="PDF" class="form-control" />
                        @Html.ValidationMessageFor(model => model.PDFFileUrl, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>İmtahan Görünsün:<span style="color:red">*</span></p>
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>İmtahan Aktivdir:<span style="color:red">*</span></p>
                        @Html.EditorFor(model => model.Giris)
                        @Html.ValidationMessageFor(model => model.Giris, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @*<div class="col-lg-4">
                <div class="form-group">
                    <div class="col-md-12">
                        <p>Admin:<span style="color:red">*</span></p>
                        @Html.DropDownList("AdminID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.AdminID, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Yarat" class="btn btn-outline-info" />
                <a href="/Exam/Index" class="btn btn-outline-dark">Geri</a>
            </div>
        </div>
    </div>
}


<!-- jQuery -->
<script src="~/assets/vendor/jquery.min.js"></script>

<!-- jQuery Mask Plugin -->
<script src="~/assets/vendor/jquery.mask.min.js"></script>

ExamAndQuiz/Views/Exam/Edit.cshtml
@model ExamAndQuiz.Models.Exam

@{
    ViewBag.Title = "Yenilə";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
}

<h2>Yenilə</h2>

@using (Html.BeginForm("Edit", "Exam", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.FotoURL)
        @Html.HiddenFor(model => model.PDFFileUrl)
        <input type="hidden" name="@Html.NameFor(x => x.AdminID)" value="@Session["ID"]" />
        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SinifID, "SinifID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SinifID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SinifID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="DogumTarixi" value="@Model.Tarix.ToShortDateString()" class="form-control" required="" />

                @Html.ValidationMessageFor(model => model.Tarix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Saat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Saat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Saat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Muddet_deqiqe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Muddet_deqiqe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Muddet_deqiqe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Giris, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Giris)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <p>Imtahan:<span style="color:red">*</span></p>
                <div class="col-md-10" style="padding:0; margin:0">
                    <select name="@Html.NameFor(x => x.Imtahan)" id="file" class="form-control">
                        @*<option value="@Model.Imtahan">--seç--</option>*@
                        <option value="Sınaq">Sınaq</option>
                        @*<option value="Quiz">Quiz</option>*@
                    </select>
                    @Html.ValidationMessageFor(model => model.FotoURL, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoURL, htmlAttributes: new { @class = "control-label col-md-2" }) <span style="background-color:lightgray"> @Model.FotoURL </span>
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" value="" />
                @Html.ValidationMessageFor(model => model.FotoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoURL, htmlAttributes: new { @class = "control-label col-md-2" }) <span style="background-color:lightgray"> @Model.PDFFileUrl </span>
            <div class="col-md-10">
                <input type="file" name="PDF" id="PDF" class="form-control" value="" />
                @Html.ValidationMessageFor(model => model.FotoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipParametrID, "TipParametrID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipParametrID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipParametrID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.AdminID, "AdminID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AdminID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AdminID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Yenilə" class="btn btn-outline-info" />
                <a href="/Exam/Index" class="btn btn-outline-dark">Geri</a>
            </div>
        </div>
    </div>
}

ExamAndQuiz/Views/Exam/Index.cshtml
@model IEnumerable<ExamAndQuiz.Models.Exam>

@{
    ViewBag.Title = "İmtahanlar";
    Layout = "~/Views/Shared/_LayoutBack.cshtml";
}

<h2>İmtahanlar</h2>

<p>
    <a href="/Exam/Create" class="btn btn-outline-dark">Yeni İmtahan</a>
</p>
<table id="zero_config" class="table table-bordered table-hover">
    <thead>
        <tr>
            @*<th>
                Növü
            </th>*@
            <th>
                Adı
            </th>
            <th>
                Sinifi
            </th>
            <th>
                Tarixi
            </th>
            <th>
                Saatı
            </th>
            <th>
                Muddeti
            </th>
            <th>
                Görünsün
            </th>
            <th>
                Aktivdir
            </th>
            <th>
                Foto
            </th>
            <th>
                PDF
            </th>
            <th>
                Admin
            </th>
            <th>
                İmtahan Tipi
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Imtahan)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Ad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade.ID)
                </td>
                <td>
                    @item.Tarix.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Saat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Muddet_deqiqe)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Giris)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FotoURL)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PDFFileUrl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Admin.Ad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamTypeParameter.Ad)
                </td>
                <td style="width:100px; text-align:center">
                    <a href="/Exam/Edit/@item.ID"><i class="fa fa-edit" style="color:green"></i></a> |
                    <a href="/ExamQuestion/Index/@item.ID"><i class="fa fa-desktop" style="color:mediumpurple"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>